services:
  - type: web
    name: springboot-backend
    env: java
    plan: free
    rootDir: server
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/*.jar"
    autoDeploy: true
